"""Regenerate specialist/broad/mixed experiment configs. Specialists draw ONE
topic at RUN TIME from the k=50 pool (configs/topics-k50.yaml, generated from
data/stage1/topics_k50.json) via read/write_topics: "random" — assignment is
seeded, distinct within a run, and recorded in run_meta.json.
Run: uv run python scripts/gen_topic_configs.py"""
import json

import yaml

MASS = 800  # equal-mass regions: each topic scope = its 800 nearest corpus papers
topics = json.load(open("data/stage1/topics_k50.json"))
yaml.safe_dump({"mass": MASS, "topics": topics},
               open("configs/topics-k50.yaml", "w"), allow_unicode=True)


def spec_agent(aid):
    return {"agent_id": aid, "policy": "llm",
            "read_topics": "random", "read_mass": MASS,
            "write_topics": "random", "write_mass": MASS}


def broad_agent(aid):
    return {"agent_id": aid, "policy": "llm",
            "write_topics": "random", "write_mass": MASS}


def gen_agent(aid):
    return {"agent_id": aid, "policy": "llm"}


HEADER = ("# GENERATED by scripts/gen_topic_configs.py.\n"
          "# Specialists get ONE random topic from configs/topics-k50.yaml per run\n"
          "# (seeded, distinct within a run, recorded in run_meta.json).\n"
          "# Edit the generator, not this file.\n")


def write(path, run_id, agents, comment):
    cfg = {"extends": "../stage1.yaml",
           "run": {"run_id": run_id, "seed": 0, "total_steps": 400,
                   "generation_budget": 40, "agents": agents}}
    with open(path, "w") as f:
        f.write(HEADER + f"# {comment}\n")
        yaml.safe_dump(cfg, f, allow_unicode=True, sort_keys=False, width=100)


write("configs/experiments/core-specialists.yaml", "core-specialists",
      [spec_agent(f"s{i}") for i in range(10)],
      "C2 core: 10 specialists, each reads+writes one random topic")
write("configs/experiments/core-broad.yaml", "core-broad",
      [broad_agent(f"b{i}") for i in range(10)],
      "C3 core: 10 broad readers / local writers (read all, write one random topic)")
write("configs/experiments/core-mixed.yaml", "core-mixed",
      [spec_agent(f"s{i}") for i in range(4)]
      + [broad_agent(f"b{i}") for i in range(3)]
      + [gen_agent(f"g{i}") for i in range(3)],
      "C4 core: mixed team = 4 specialists + 3 broad + 3 generalists")
write("configs/experiments/supp-mixed-spec-heavy.yaml", "supp-mixed-spec-heavy",
      [spec_agent(f"s{i}") for i in range(7)] + [gen_agent(f"g{i}") for i in range(3)],
      "supplementary composition sweep: 7 specialists + 3 generalists")
write("configs/experiments/supp-mixed-gen-heavy.yaml", "supp-mixed-gen-heavy",
      [spec_agent(f"s{i}") for i in range(3)] + [gen_agent(f"g{i}") for i in range(7)],
      "supplementary composition sweep: 3 specialists + 7 generalists")
print("configs regenerated")
