"""Regenerate paper 2's k-sweep configs (spec §6, stage 1).

k in {1,2,4,8,16,32} then every 16 up to 128 (48,64,80,96,112,128),
at N=10, 100 rounds = 1000 steps — the same per-agent
depth as paper 1's core runs.
k=128 is the whole pool: the generalist endpoint, every agent interested
in everything. It is the analogue of paper 1's m=infinity condition.
Run: uv run python scripts/gen_forum_configs.py
"""
from pathlib import Path

import yaml

KS = [1, 2, 4, 8, 16, 32, 48, 64, 80, 96, 112, 128]
N = 10
ROUNDS = 100

HEADER = ("# GENERATED by scripts/gen_forum_configs.py.\n"
          "# Each agent draws k distinct topics from configs/p2_forum/topics-k128.yaml\n"
          "# (seeded, recorded in run_meta.json). Agents may share topics.\n"
          "# Edit the generator, not this file.\n")

out_dir = Path("configs/p2_forum/experiments")
out_dir.mkdir(parents=True, exist_ok=True)
for k in KS:
    cfg = {"extends": "../base.yaml",
           "run": {"run_id": f"forum-k{k}", "seed": 0,
                   "total_steps": ROUNDS * N,
                   "agents": [{"agent_id": f"a{i}", "k_topics": k}
                              for i in range(N)]}}
    path = out_dir / f"k{k}.yaml"
    with path.open("w") as f:
        f.write(HEADER + f"# k={k}: {N} agents, each interested in {k} topics\n")
        yaml.safe_dump(cfg, f, allow_unicode=True, sort_keys=False, width=100)
print(f"{len(KS)} configs regenerated in {out_dir}")

# ---- nested sweep ------------------------------------------------------------
# Topics are nested across k (each agent takes the first k topics of its own
# seed-determined permutation), so adjacent k differ only by the added topics.
# One config per (k, seed) with its own run_id, so a run is extended later by
# re-running the SAME config with --resume --steps <new total>.
NESTED_KS = [1, 16, 32, 48, 64, 80, 96, 112, 128]
NESTED_SEEDS = [0, 1, 2]
NESTED_ROUNDS = 40

nested_dir = out_dir / "nested"
nested_dir.mkdir(parents=True, exist_ok=True)
for k in NESTED_KS:
    for s in NESTED_SEEDS:
        cfg = {"extends": "../../base.yaml",
               "run": {"run_id": f"forum-nested-k{k}-s{s}", "seed": s,
                       "total_steps": NESTED_ROUNDS * N,
                       "topic_draw": "nested",
                       "agents": [{"agent_id": f"a{i}", "k_topics": k}
                                  for i in range(N)]}}
        with (nested_dir / f"k{k}-s{s}.yaml").open("w") as f:
            f.write(HEADER.replace("draws k distinct topics",
                                   "takes the first k topics of its own seeded permutation")
                    + f"# nested k={k}, seed {s}: {N} agents, {NESTED_ROUNDS} rounds; "
                      f"extend with --resume --steps <total>\n")
            yaml.safe_dump(cfg, f, allow_unicode=True, sort_keys=False, width=100)
print(f"{len(NESTED_KS) * len(NESTED_SEEDS)} nested configs regenerated in {nested_dir}")

# ---- online sweep ------------------------------------------------------------
# Online literature + hard topic gating (base-online.yaml), on the nested draw.
# One seed per k (user decision 2026-10-01).
ONLINE_KS = NESTED_KS
ONLINE_SEEDS = [0]
ONLINE_ROUNDS = 40

online_dir = out_dir / "online"
online_dir.mkdir(parents=True, exist_ok=True)
for k in ONLINE_KS:
    for s in ONLINE_SEEDS:
        cfg = {"extends": "../../base-online.yaml",
               "run": {"run_id": f"forum-online-k{k}-s{s}", "seed": s,
                       "total_steps": ONLINE_ROUNDS * N,
                       "topic_draw": "nested",
                       "agents": [{"agent_id": f"a{i}", "k_topics": k}
                                  for i in range(N)]}}
        with (online_dir / f"k{k}-s{s}.yaml").open("w") as f:
            f.write(HEADER.replace("draws k distinct topics",
                                   "takes the first k topics of its own seeded permutation")
                          .replace("topics-k128.yaml", "topics-v2.yaml")
                    + f"# online k={k}, seed {s}: {N} agents, {ONLINE_ROUNDS} rounds, "
                      f"online literature + topic gating; extend with --resume --steps <total>\n")
            yaml.safe_dump(cfg, f, allow_unicode=True, sort_keys=False, width=100)
print(f"{len(ONLINE_KS) * len(ONLINE_SEEDS)} online configs regenerated in {online_dir}")

# ---- region sweep ------------------------------------------------------------
# Frozen corpus + semantic-region gating (base-region.yaml, spec REVISION
# 2026-10-06): every agent reads the coverage x N corpus papers nearest to its
# own seeded seed paper. One seed per coverage.
REGION_PCTS = [1, 5, 10, 20, 30, 40, 50, 100]
REGION_SEEDS = [0]
REGION_ROUNDS = 40

region_dir = out_dir / "region"
region_dir.mkdir(parents=True, exist_ok=True)
for pct in REGION_PCTS:
    for s in REGION_SEEDS:
        cfg = {"extends": "../../base-region.yaml",
               "run": {"run_id": f"forum-region-c{pct}-s{s}", "seed": s,
                       "total_steps": REGION_ROUNDS * N,
                       "agents": [{"agent_id": f"a{i}", "coverage": pct / 100}
                                  for i in range(N)]}}
        with (region_dir / f"c{pct}-s{s}.yaml").open("w") as f:
            f.write("# GENERATED by scripts/gen_forum_configs.py. Edit the generator, not this file.\n"
                    f"# region coverage {pct}%, seed {s}: {N} agents, {REGION_ROUNDS} rounds; each "
                    "agent reads the\n# corpus papers nearest to its seed paper (seeded, recorded "
                    "in run_meta.json);\n# extend with --resume --steps <total>\n")
            yaml.safe_dump(cfg, f, allow_unicode=True, sort_keys=False, width=100)
print(f"{len(REGION_PCTS) * len(REGION_SEEDS)} region configs regenerated in {region_dir}")
