"""Regenerate specialist/broad/mixed experiment configs from the k=40 topic
pool (data/stage1/topics_k40.json -> configs/topics-k40.yaml). Topics are
greedily bundled into 10 thematically-coherent groups of 4 by embedding
similarity of their names; each specialist agent holds one bundle (multi-
anchor semantic scope). Run: uv run python scripts/gen_topic_configs.py"""
import json

import yaml

from innovation.ideas.embed import Embedder

RADIUS = 0.3
topics = json.load(open("data/stage1/topics_k40.json"))
names = [t["topic"] for t in topics]
yaml.safe_dump({"radius": RADIUS, "topics": topics},
               open("configs/topics-k40.yaml", "w"), allow_unicode=True)

emb = Embedder("BAAI/bge-small-en-v1.5")
vecs = emb.encode(names)
unassigned = set(range(len(names)))
bundles = []
while unassigned:
    seed_i = min(unassigned)
    unassigned.discard(seed_i)
    sims = vecs @ vecs[seed_i]
    nearest = sorted(unassigned, key=lambda j: -sims[j])[:3]
    for j in nearest:
        unassigned.discard(j)
    bundles.append([names[seed_i]] + [names[j] for j in nearest])

def spec_agent(aid, bundle):
    return {"agent_id": aid, "policy": "llm",
            "read_topics": bundle, "read_radius": RADIUS,
            "write_topics": bundle, "write_radius": RADIUS}

def broad_agent(aid, bundle):
    return {"agent_id": aid, "policy": "llm",
            "write_topics": bundle, "write_radius": RADIUS}

def gen_agent(aid):
    return {"agent_id": aid, "policy": "llm"}

HEADER = ("# GENERATED by scripts/gen_topic_configs.py from configs/topics-k40.yaml\n"
          "# (40 corpus-derived topics, 10 thematic bundles of 4; radius 0.3).\n"
          "# Edit the generator, not this file.\n")

def write(path, run_id, agents, comment):
    cfg = {"extends": "../stage1.yaml",
           "run": {"run_id": run_id, "seed": 0, "total_steps": 400,
                   "generation_budget": 40, "agents": agents}}
    with open(path, "w") as f:
        f.write(HEADER + f"# {comment}\n")
        yaml.safe_dump(cfg, f, allow_unicode=True, sort_keys=False, width=100)

write("configs/experiments/core-specialists.yaml", "core-specialists",
      [spec_agent(f"s{i}", bundles[i]) for i in range(10)],
      "C2 core: 10 specialists, each reads+writes its own 4-topic bundle")
write("configs/experiments/core-broad.yaml", "core-broad",
      [broad_agent(f"b{i}", bundles[i]) for i in range(10)],
      "C3 core: 10 broad readers / local writers (read all, write own bundle)")
write("configs/experiments/core-mixed.yaml", "core-mixed",
      [spec_agent(f"s{i}", bundles[i]) for i in range(4)]
      + [broad_agent(f"b{i}", bundles[4 + i]) for i in range(3)]
      + [gen_agent(f"g{i}") for i in range(3)],
      "C4 core: mixed team = 4 specialists + 3 broad + 3 generalists")
write("configs/experiments/supp-mixed-spec-heavy.yaml", "supp-mixed-spec-heavy",
      [spec_agent(f"s{i}", bundles[i]) for i in range(7)]
      + [gen_agent(f"g{i}") for i in range(3)],
      "supplementary composition sweep: 7 specialists + 3 generalists")
write("configs/experiments/supp-mixed-gen-heavy.yaml", "supp-mixed-gen-heavy",
      [spec_agent(f"s{i}", bundles[i]) for i in range(3)]
      + [gen_agent(f"g{i}") for i in range(7)],
      "supplementary composition sweep: 3 specialists + 7 generalists")
print("bundles:")
for i, b in enumerate(bundles):
    print(f"  {i}: {b}")
