"""Regenerate paper 2's k-sweep configs (spec §6, stage 1).

k in {1,2,4,8,16,32,64} at N=10, 80 rounds = 800 steps — the same per-agent
depth as paper 1's core runs.
Run: uv run python scripts/gen_forum_configs.py
"""
from pathlib import Path

import yaml

KS = [1, 2, 4, 8, 16, 32, 64]
N = 10
ROUNDS = 80

HEADER = ("# GENERATED by scripts/gen_forum_configs.py.\n"
          "# Each agent draws k distinct topics from configs/p2_forum/topics-k128.yaml\n"
          "# (seeded, recorded in run_meta.json). Agents may share topics.\n"
          "# Edit the generator, not this file.\n")

out_dir = Path("configs/p2_forum/experiments")
out_dir.mkdir(parents=True, exist_ok=True)
for k in KS:
    cfg = {"extends": "../base.yaml",
           "run": {"run_id": f"forum-k{k}", "seed": 0,
                   "total_steps": ROUNDS * N,
                   "agents": [{"agent_id": f"a{i}", "k_topics": k}
                              for i in range(N)]}}
    path = out_dir / f"k{k}.yaml"
    with path.open("w") as f:
        f.write(HEADER + f"# k={k}: {N} agents, each interested in {k} topics\n")
        yaml.safe_dump(cfg, f, allow_unicode=True, sort_keys=False, width=100)
print(f"{len(KS)} configs regenerated in {out_dir}")
